// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type People struct {
	ID   string `json:"id"`
	Name string `json:"name"`
}

type Todo struct {
	ID   string `json:"id"`
	Text string `json:"text"`
	Done bool   `json:"done"`
}

type User struct {
	ID     string    `json:"id"`
	Name   string    `json:"name"`
	Todos  []*Todo   `json:"todos"`
	People []*People `json:"people"`
	Inflow int       `json:"inflow"`
}
